### ISSUE TITLE
 Bug: Incorrect equality check for different object order in array

### ISSUE THREAD

**Issue by sheruniferdo** [Pasan-Kottearachchi/primitive-deep-equal#1]
When the order of objects within arrays differs, the equality check returns false, even though the objects are identical in content.

**Expected Behavior**: The isEqual function should return true when the arrays contain identical objects, regardless of their order.

**Comment by Pasan-Kottearachchi** [comment]
Please have a look into this PR. This should sort the issue

https://github.com/Pasan-Kottearachchi/primitive-deep-equal/pull/2
